### ISSUE TITLE
Invert findByProp

### ISSUE THREAD

**Issue by maluramichael** [skellock/ramdasauce#6]
Would be nice to have a function which rejects everything that matches the prop.

``` javascript
import R from 'ramda'

/**
 * Rejects any object in an array by the given property and value.
 *
 * @since v1.0.1
 * @param {prop} (String) The prop to search by.
 * @param {value} (String) The string to search for.
 * @param {source} (Array) The array to search in.
 * @return {Object} The object that matches the search or null if not found.
 * @example
 * RS.rejectByProp('id', 'a', [{id: 'a'}, {id: 'b'}]) //=> {id: 'b'}
 */
const rejectByProp = R.curry(
  (prop, value, source) => R.reject(R.propEq(prop, value))(source)
)

export default rejectByProp
```

**Comment by skellock** [comment]
Sounds good!  I'm just on vacation now, but I can do this when I get back.

**Comment by skellock** [comment]
I don't always take a vacation, but when I do, it's 5 months long.

```js
RS.rejectByProp('id', 'a', [{id: 'a'}, {id: 'b'}])
// vs.
R.reject(R.propEq('id, 'a'), [{id: 'a'}, {id: 'b'}])
```

There's not a whole lot of savings here, so I think I'm going to skip on this one.

When I look back at some of functions that we have already, I do kinda question some of them. Like our `findByProp` and `eqLength`.

So I'm trying to stay away from the ones that are just predicate wrappers.

100% appreciate you taking the time to file this issue though.
